export enum Role {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  HOTEL = 'HOTEL',
  AGENT = 'AGENT',
  TOUR_GUIDE = 'TOUR_GUIDE',
  ADMIN = 'ADMIN',
  CALL_CENTER = 'CALL_CENTER',
}

export enum AppointmentType {
  HOUSE_CALL = 'HOUSE_CALL',
  TELE_CONSULTATION = 'TELE_CONSULTATION',
  MEDICAL_VISIT = 'MEDICAL_VISIT',
}

export enum AppointmentStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CREDIT_USED = 'CREDIT_USED',
}

export enum PaymentMethod {
  PAYMENT_LINK = 'PAYMENT_LINK',
  CREDIT_LIMIT = 'CREDIT_LIMIT',
}
